### ISSUE TITLE
Don't tie collections to filesystem hierarchy

### ISSUE THREAD

**Issue by progfolio** [Whil-/org-collection#1]
I like the general idea you have here, but I don't see any reason to tie the collection to a specific directory. I would look into how `org-agenda-files` works. It would be much more flexible to be able to add any list of files/directories per collection. They could exist anywhere on disk and still be associated with the proper collection. This would also obviate the need for the collection configuration to be scattered across the file system. Also, consider the case where one moves a file on disk. If the collection is associated with the directory, that association is lost if they file is moved.

A single global variable can still be used to manage these collections, similar to the way one manages `org-capture-templates` with a single list. (e.g. org-collections). This variable could be set in the init file, appended to as needed in other files, manipulated from a directory-local file, etc.

**Comment by Whil-** [comment]
Hi,

Thanks for your comments! The initial idea I had for this package was very much similar to how you describe it, where a user would specify her own logic for determining what files and folders a collection should contain. But I couldn't figure out how to make that work in a composable and intuitive way. Doesn't mean it isn't possible of course. But in the end this folder-based solution was chosen. After procrastinating way to long on it. You'll see some discussions around declaring a collection as a specification according to the above if you read through my initial pitch (linked in the readme) and some comments about the idea on the list.

On to the point of using a directory as the base of a collection then; One benefit is that a collection becomes easily exportable between systems and users. Check in the configuration together the files inside Git and sync away. For collaboration purposes that should be a plus. With folders, collections are also very easy to reason about. They act as a root in a directory-tree of files, declares some defaults on that root to make it work across files and the rest is up to the collection-owner(s). There is really nothing stopping you from declaring `org-agenda-files` as something customizable (and complex) within a collection. Or to make something complex within that collection. My intention is for collections to be aware of subfolders, so one collection can contain multiple folders and all would still be within the same collection, unless a subfolder in it self has a sub-collection declared. This, however, isn't implemented yet..

After having worked with this and thought about it some, I like the idea of something simple (collection tied to a folder) instead of the `org-agenda-files` approach. One can still think about graphs and more complicated things within a collection, using other packages such as org-brain or org-roam or similar. This package composes well with everything else, since it just let you create local collections in which you can customize whatever you wish (as long as it's about Org).

Ideally one should be able to look at an Org collection without having to think about Emacs. So the less ties to a global config, the better in my view (right now).

> Also, consider the case where one moves a file on disk. If the collection is associated with the directory, that association is lost if they file is moved.
The same would be true if using the `org-agenda-files` way of specifying a collection, if a file is moved or renamed to not be a part of that specification. I guess what I'm trying to say is that it's expected to be like that. A directory (with a defined collection) declares the context and moving a file outside of that context will, expectedly, also remove the relation that file has to the collection. Makes sense?

**Comment by progfolio** [comment]
I started a rough implementation of my own. I quickly realized there is no reason to limit what I'm envisioning to Org, though. Did some more research and someone has implemented something closer to what I'm imagining (Though, this falls short IMO, too): https://github.com/e-user/contextual

**Comment by Whil-** [comment]
Okay, looking forward to seeing what you accomplish. Cheers 🥂

**Comment by progfolio** [comment]
Thank you. Likewise.
