### ISSUE TITLE
Project Rename

### ISSUE THREAD

**Issue by progfolio** [Whil-/org-collection#2]
There is precedent in Org and other packages for the term "context". e.g. mu4e-contexts, org-capture-template-contexts, org-agenda-custom-commands-contexts. If I understand correctly, the goal of the package is to provide contextual configuration for Org mode. The term "collection" doesn't make this immediately clear. 
Org has already used `org-context` as a function, but `org-contexts` is available. I could see the argument for that being confusing (though I dont find it to be). Perhaps `org-profiles`, `org-user-profiles`, `org-user-contexts`, `org-config-contexts`?

**Comment by Whil-** [comment]
Hi,

The goal of the package is more about tying together sets of files into ... something. The package should promote the idea of making things local instead of configuring things globally. So the intention is less about configuring user contexts and more about defining sets of files and being able to work with them together. The implication and solution may be very similar, but it's kind of looking at the problem from different angles. Do you follow my reasoning?

So for now I don't see any reason for renaming it into something else than "org collection", even if `org-contexts` as well provides a good description of what the package does today.

**Comment by progfolio** [comment]
> The goal of the package is more about tying together sets of files into ... something.

The "something" is a context.

> The implication and solution may be very similar, but it's kind of looking at the problem from different angles. Do you follow my reasoning?

I do understand what you are trying to achieve, but I feel like the implementation is more rigid than it needs to be.
Perhaps I'll take a crack at my own implementation and we can compare ideas.

**Comment by Whil-** [comment]
> The "something" is a context

And a collection. And a project. And an area. And surely a bunch of other words representing similar things. Anyhow, I've chosen the word collection to put the emphasis on it being about creating that something out of more than one Org mode file, and being able to reason about that something as a collection. But that name doesn't mean it can't be thought about as something else. I'm not at all against that perspective. Just arguing that the name is what it is. A name is also something somewhat in the eyes of the beholder. A single word can only tell so much of the story. So it's bound to be somewhat up for interpretation. Anyway, to summarize, I don't see any compelling reason for a rename.

> I do understand what you are trying to achieve, but I feel like the implementation is more rigid than it needs to be.
Perhaps I'll take a crack at my own implementation and we can compare ideas.

Sure, please do! Interesting!
